
const map = {
    "PRODUTOS": "ID_PRODUTO",
    "PESSOAS": "ID_PESSOA",
    "CONTRATOS": "ID_CONTRATO",
    "CATEGORIAS": "ID_CATEGORIA",
    "CATEGORIA_DETALHE": "ID_CATEGORIA_DETALHE",
    "FINANCEIRO":"ID_FINANCEIRO",
    "FINANCEIRO_DOCUMENTOS": "ID_FINANCEIRO_DOCUMENTO",
    "ENTIDADES": "ID_ENTIDADE",
    "CONTAS":"ID_CONTA",
    "MOVIMENTACOES":"ID_MOVIMENTACAO",
    "ESTOQUE":"ID_ESTOQUE"
}

module.exports = {
    map: map
}