CREATE TABLE CATEGORIAS (
	ID_CATEGORIA	INT PRIMARY KEY AUTO_INCREMENT	,
    ID_ENTIDADE		INT NOT NULL					,
    CD_CATEGORIA	INT NOT NULL					,
    TP_CATEGORIA	VARCHAR(1) NOT NULL				,
    NM_CATEGORIA	VARCHAR(50) NOT NULL			,
    SN_ATIVO		BOOLEAN							,
    HISTORICO		VARCHAR(250)					,
    
    FOREIGN KEY (ID_ENTIDADE) REFERENCES ENTIDADES(ID_ENTIDADE)	,
    CONSTRAINT CD_CATEGORIA UNIQUE (ID_ENTIDADE, CD_CATEGORIA)
    );

CREATE TABLE CATEGORIA_DETALHE (
	ID_CATEGORIA_DETALHE	INT PRIMARY KEY AUTO_INCREMENT	,
    ID_CATEGORIA			INT NOT NULL					,
    CD_DETALHE				INT NOT NULL					,
    NM_DETALHE				VARCHAR(50) NOT NULL			,
    SN_ATIVO				BOOLEAN							,
    
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS(ID_CATEGORIA),
    CONSTRAINT CD_DETALHE UNIQUE (CD_DETALHE, ID_CATEGORIA)
    );
    
CREATE TABLE CATEGORIA_ORCAMENTO (
	ID_CATEGORIA_ORCAMENTO	INT PRIMARY KEY AUTO_INCREMENT	,
    ID_CATEGORIA			INT NOT NULL					,
    DT_INICIO				DATE NOT NULL					,
    DS_ORCAMENTO			VARCHAR(50)						,
    VL_MINIMO				DECIMAL(10,2) NOT NULL			,
    VL_MEDIO				DECIMAL(10,2) NOT NULL			,
    VL_MAXIMO				DECIMAL(10,2) NOT NULL			,
    
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS(ID_CATEGORIA)	,
    CONSTRAINT DT_INICIO UNIQUE (ID_CATEGORIA, DT_INICIO)
    );