CREATE TABLE CONTAS (
	ID_CONTA	INT PRIMARY KEY AUTO_INCREMENT	,
    ID_ENTIDADE	INT NOT NULL					,
    CD_CONTA	VARCHAR(15) NOT NULL			,
    DG_CONTA	VARCHAR(2) NOT NULL				,
    CD_AGENCIA	VARCHAR(6)						,
    DS_CONTA	VARCHAR(100)NOT NULL			,
    SN_ATIVO	BOOLEAN							,
    HISTORICO	VARCHAR(250)					,
    
    FOREIGN KEY (ID_ENTIDADE) REFERENCES ENTIDADES(ID_ENTIDADE)	,
    CONSTRAINT CD_CONTA UNIQUE (ID_ENTIDADE, CD_CONTA, DG_CONTA)
    );