CREATE TABLE CONTRATOS (
	ID_CONTRATO 	INT PRIMARY KEY AUTO_INCREMENT	,
    ID_ENTIDADE 	INT NOT NULL					,
    CD_CONTRATO		VARCHAR(15) NOT NULL			,
    ID_PESSOA		INT NOT NULL					,
    DT_ASSINATURA	DATE NOT NULL					,
    DT_TERMINO		DATE NOT NULL					,
    VL_CONTRATO		DECIMAL(10,2) NOT NULL			,
    HISTORICO		VARCHAR(500) NOT NULL			,
    
    FOREIGN KEY (ID_ENTIDADE) REFERENCES ENTIDADES(ID_ENTIDADE)	,
    FOREIGN KEY (ID_PESSOA) REFERENCES PESSOAS(ID_PESSOA)		,
    CONSTRAINT CD_CONTRATO UNIQUE (ID_ENTIDADE, CD_CONTRATO)	
    );
    
ALTER TABLE CONTRATOS ADD COLUMN CD_STATUS VARCHAR(1) NOT NULL;
ALTER TABLE CONTRATOS ADD COLUMN DS_CONTRATO VARCHAR(100) NOT NULL;
ALTER TABLE CONTRATOS MODIFY COLUMN HISTORICO VARCHAR(500);
    
CREATE TABLE CONTRATO_ADITIVO (
	ID_ADITIVO		INT PRIMARY KEY AUTO_INCREMENT	,
    ID_CONTRATO		INT NOT NULL					,
    CD_ADITIVO		VARCHAR(15) NOT NULL			,
    DT_ASSINATURA 	DATE NOT NULL					,
    DT_TERMINO		DATE NOT NULL					,
    VL_ADITIVO		DECIMAL(10,2) NOT NULL			,
    
    FOREIGN KEY (ID_CONTRATO) REFERENCES CONTRATOS(ID_CONTRATO)	,
    CONSTRAINT CD_ADITIVO UNIQUE (ID_CONTRATO, CD_ADITIVO)
    );
    
    