SELECT
	C.ID_CATEGORIA				,
    C.NM_CATEGORIA				,
    CO.VL_MINIMO				,
    CO.VL_MEDIO					,
    CO.VL_MAXIMO				,
    
    COALESCE(SUM(RECEITA), 0)	AS TOTAL_RECEITA	,
    COALESCE(SUM(DESPESA), 0)	AS TOTAL_DESPESA
FROM CATEGORIAS C
	INNER JOIN CATEGORIA_DETALHE	CD	ON CD.ID_CATEGORIA			= C.ID_CATEGORIA
	INNER JOIN CATEGORIA_ORCAMENTO 	CO	ON CO.ID_CATEGORIA 			= C.ID_CATEGORIA
    
    LEFT JOIN (
    
    SELECT
		IF(TP_FINANCEIRO = 'R', VL_FINANCEIRO, 0) AS RECEITA	,
		IF(TP_FINANCEIRO = 'D', VL_FINANCEIRO, 0) AS DESPESA	,
		ID_CATEGORIA_DETALHE
	FROM FINANCEIRO WHERE ID_ENTIDADE = 3
    AND MONTH(DT_FINANCEIRO) = 6 AND YEAR(DT_FINANCEIRO) = 2026
    
    UNION ALL
    
    SELECT
		0 AS RECEITA											,
        VL_ESTOQUE AS DESPESA									,
        ID_CATEGORIA_DETALHE
	FROM ESTOQUE WHERE TP_ESTOQUE = 'E' AND CD_STATUS = 'E' AND ID_ENTIDADE = 3
    AND MONTH(DT_ESTOQUE) = 6 AND YEAR(DT_ESTOQUE) = 2026
    
    UNION ALL
    
    SELECT
		VL_MOVIMENTACAO AS RECEITA								,
		0 AS DESPESA											,
        ID_CATEGORIA_DETALHE
	FROM MOVIMENTACOES WHERE CD_STATUS = 'P' AND ID_ENTIDADE = 3
    AND MONTH(DT_MOVIMENTACAO) = 6 AND YEAR(DT_MOVIMENTACAO) = 2026
    
    ) T ON T.ID_CATEGORIA_DETALHE = CD.ID_CATEGORIA_DETALHE

WHERE C.ID_ENTIDADE = 3
	AND CO.DT_INICIO = (SELECT MAX(CO2.DT_INICIO) FROM CATEGORIA_ORCAMENTO CO2 WHERE C.ID_CATEGORIA = CO2.ID_CATEGORIA)
GROUP BY 1, 2, 3, 4, 5
;