-- RECEITA TOTAL
SELECT SUM(VL_FINANCEIRO) FROM FINANCEIRO WHERE TP_FINANCEIRO = 'R' AND ID_ENTIDADE = 2;
SELECT SUM(VL_MOVIMENTACAO) FROM MOVIMENTACOES WHERE CD_STATUS IN ('L','P') AND ID_ENTIDADE = 2;

-- TOTAL DESPESAS
SELECT SUM(VL_FINANCEIRO) FROM FINANCEIRO WHERE TP_FINANCEIRO = 'D' AND ID_ENTIDADE = 2;
SELECT SUM(VL_ESTOQUE) FROM ESTOQUE WHERE TP_MOVIMENTACAO = 'E' AND ID_ENTIDADE = 2;

-- SELECT FINAL
SELECT
	COALESCE(F.RECEITA, 0) + COALESCE(M.RECEITA, 0) AS RECEITA,
    COALESCE(F.DESPESA, 0) + COALESCE(E.DESPESA, 0) AS DESPESA
FROM (
	SELECT
		SUM(IF(TP_FINANCEIRO = 'R', VL_FINANCEIRO, 0)) AS RECEITA,
        SUM(IF(TP_FINANCEIRO = 'D', VL_FINANCEIRO, 0)) AS DESPESA
	FROM FINANCEIRO WHERE CD_STATUS = 'P' AND ID_ENTIDADE = 2
    AND MONTH(DT_FINANCEIRO) = 5 AND YEAR(DT_FINANCEIRO) = 2026) F
	
JOIN (
	SELECT
		SUM(VL_MOVIMENTACAO) AS RECEITA
	FROM MOVIMENTACOES WHERE CD_STATUS = 'P' AND ID_ENTIDADE = 2
    AND MONTH(DT_MOVIMENTACAO) = 5 AND YEAR(DT_MOVIMENTACAO) = 2026) M

JOIN (
	SELECT
		SUM(VL_ESTOQUE) AS DESPESA
	FROM ESTOQUE WHERE TP_ESTOQUE = 'E' AND CD_STATUS = 'E' AND ID_ENTIDADE = 2
    AND MONTH(DT_ESTOQUE) = 5 AND YEAR(DT_ESTOQUE) = 2026) E;