SELECT
	P.ID_PRODUTO	,
    P.NM_PRODUTO	,
    P.UN_MEDIDA		,
    PE.MIN_ESTOQUE	,
    PE.MED_ESTOQUE	,
    PE.MAX_ESTOQUE	,
    T.QT_SALDO		,
    
    AVG(I.VL_UNITARIO) AS VL_UNITARIO		,
    (AVG(I.VL_UNITARIO) * QT_SALDO) AS VL_TOTAL
FROM PRODUTOS P
	INNER JOIN ESTOQUE_ITENS 	I ON P.ID_PRODUTO = I.ID_PRODUTO
    
    INNER JOIN ESTOQUE			E ON I.ID_ESTOQUE = E.ID_ESTOQUE
    AND E.TP_ESTOQUE = 'E' 		AND E.CD_STATUS = 'E'
    AND E.DT_ESTOQUE = (
		SELECT MAX(E2.DT_ESTOQUE) 
		FROM ESTOQUE E2 
        INNER JOIN ESTOQUE_ITENS I2 ON E2.ID_ESTOQUE = I2.ID_ESTOQUE
		WHERE P.ID_PRODUTO = I2.ID_PRODUTO
        AND E2.TP_ESTOQUE = 'E' AND E2.CD_STATUS = 'E'
	)
    
    INNER JOIN PRODUTO_ESTOQUE PE ON PE.ID_PRODUTO = P.ID_PRODUTO
	AND PE.DT_INICIO = (
		SELECT MAX(PE2.DT_INICIO)
		FROM PRODUTO_ESTOQUE PE2
		WHERE PE2.ID_PRODUTO = P.ID_PRODUTO
	)
    
    LEFT JOIN (
		SELECT I3.ID_PRODUTO,
		SUM(IF(E3.TP_ESTOQUE = 'E', I3.QT_ITENS, -I3.QT_ITENS)) AS QT_SALDO
		FROM ESTOQUE E3
		JOIN ESTOQUE_ITENS I3 ON E3.ID_ESTOQUE = I3.ID_ESTOQUE
		WHERE E3.CD_STATUS = 'E' AND E3.ID_ENTIDADE = 4
		GROUP BY I3.ID_PRODUTO
	) T ON T.ID_PRODUTO = P.ID_PRODUTO
    
WHERE P.ID_ENTIDADE = 4 GROUP BY 1, 2, 3, 4, 5, 6, 7 ;