CREATE DATABASE DB1003;

USE DB1003;

CREATE TABLE ENTIDADES(
	ID_ENTIDADE 	INT PRIMARY KEY AUTO_INCREMENT	,
    CD_ENTIDADE		INT NOT NULL UNIQUE				,
    NM_ENTIDADE		VARCHAR(100) NOT NULL			,
    CNPJ			VARCHAR(14) NOT NULL UNIQUE		
    );

INSERT INTO ENTIDADES(
	CD_ENTIDADE			,
    NM_ENTIDADE			,
    CNPJ				)
VALUES (
	'1001'				,
    'ENTIDADE MODELO'	,
    '24822967000117'	);
    
CREATE TABLE USUARIOS(
	ID_USUARIO		INT PRIMARY KEY AUTO_INCREMENT	,
    ID_ENTIDADE		INT NOT NULL					,
    CD_USUARIO		VARCHAR(25) NOT NULL			,
    NM_USUARIO		VARCHAR(50) NOT NULL			,
    HS_SENHA		VARCHAR(255) NOT NULL			,
    
    FOREIGN KEY (ID_ENTIDADE) REFERENCES ENTIDADES(ID_ENTIDADE)	,
    CONSTRAINT CD_USUARIO UNIQUE (ID_ENTIDADE, CD_USUARIO)			
    );

INSERT INTO USUARIOS (
	ID_ENTIDADE		,
    CD_USUARIO		,
    NM_USUARIO		,
    HS_SENHA		)
VALUES (
	1				,
    'ROOT'			,
    'ROOT'			,
    '$2a$12$9kFFrNuppqpq3PF1MlWH8ux67jgP95sjyjZRk5yZLqWpkwLOu2.tO'
    );