CREATE TABLE FINANCEIRO (
	ID_FINANCEIRO			INT PRIMARY KEY AUTO_INCREMENT	,
    ID_ENTIDADE				INT NOT NULL					,
    DT_FINANCEIRO			DATE NOT NULL					,
    TP_FINANCEIRO			DATE NOT NULL					,
    DS_FINANCEIRO			VARCHAR(100) NOT NULL			,
    ID_CATEGORIA			INT								,
    CD_STATUS				VARCHAR(1) NOT NULL				,
    ID_CONTRATO				INT								,
    ID_PESSOA				INT NOT NULL					,
    CD_METODO				VARCHAR(1)						,
    ID_CONTA				INT								,
    VL_FINANCEIRO			DECIMAL(10,2) NOT NULL			,
    HISTORICO				VARCHAR(250)					,
    
    FOREIGN KEY (ID_ENTIDADE) REFERENCES ENTIDADES(ID_ENTIDADE)						,
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA_DETALHE(ID_CATEGORIA_DETALHE)	,
    FOREIGN KEY (ID_CONTRATO) REFERENCES CONTRATOS(ID_CONTRATO)						,
    FOREIGN KEY (ID_PESSOA) REFERENCES PESSOAS(ID_PESSOA)							,
    FOREIGN KEY (ID_CONTA) REFERENCES CONTAS(ID_CONTA)		 
    );

CREATE TABLE FINANCEIRO_DOCUMENTOS (
	ID_FINANCEIRO_DOCUMENTO	INT PRIMARY KEY AUTO_INCREMENT	,
    ID_FINANCEIRO			INT NOT NULL					,
    DT_DOCUMENTO			DATE NOT NULL					,
    TP_DOCUMENTO			VARCHAR(1) NOT NULL				,
    DS_DOCUMENTO			VARCHAR(50) NOT NULL			,
    ANEXO					MEDIUMTEXT						
    );
    