USE DB1003;

CREATE TABLE PESSOAS(
	ID_PESSOA	INT PRIMARY KEY AUTO_INCREMENT	,
    ID_ENTIDADE	INT NOT NULL					,
    CD_PESSOA	INT NOT NULL					,
    TP_PESSOA	VARCHAR(1) NOT NULL				,
    NM_PESSOA	VARCHAR(100) NOT NULL			,
    CADASTRO	VARCHAR(14) NOT NULL			,
    SN_ATIVO	BOOLEAN NOT NULL				,
    
    FOREIGN KEY (ID_ENTIDADE) REFERENCES ENTIDADES(ID_ENTIDADE)	,
    CONSTRAINT CD_PESSOA UNIQUE (ID_ENTIDADE, CD_PESSOA)		,
    CONSTRAINT CADASTRO UNIQUE (ID_ENTIDADE, CADASTRO)
    );
    
ALTER TABLE PESSOAS ADD COLUMN HISTORICO VARCHAR(250);
    
CREATE VIEW VW_CODIGO_PESSOAS AS
	SELECT
		LPAD(COALESCE(MAX(CD_PESSOA), 0) +1, 4, '0') AS CD_PESSOA
	FROM PESSOAS;
    
DROP VIEW VW_CODIGO_PESSOAS;

CREATE VIEW VW_DATAGRID_PESSOAS AS
	SELECT
		ID_PESSOA				,
        ID_ENTIDADE				,
        LPAD(CD_PESSOA, 4, '0')	AS CD_PESSOA,
        NM_PESSOA				,
        CADASTRO				,
        
        CASE TP_PESSOA
			WHEN 'F' THEN 'Física'
            WHEN 'J' THEN 'Jurídica'
		END AS TP_PESSOA		,
        
        CASE SN_ATIVO
			WHEN 0 THEN 'Não'
            WHEN 1 THEN 'Sim'
		END AS SN_ATIVO
	FROM PESSOAS;

DROP VIEW VW_DATAGRID_PESSOAS;