CREATE TABLE PRODUTOS (
	ID_PRODUTO	INT PRIMARY KEY AUTO_INCREMENT	,
    ID_ENTIDADE	INT NOT NULL					,
    CD_PRODUTO	INT NOT NULL					,
    NM_PRODUTO	VARCHAR(100) NOT NULL			,
    TP_PRODUTO	VARCHAR(1) NOT NULL				,
    CD_BARRAS	VARCHAR(25)						,
    UN_MEDIDA	VARCHAR(25) NOT NULL			,
    ID_PESSOA	INT DEFAULT NULL				,
    NM_MARCA	VARCHAR(25)						,
    HISTORICO	VARCHAR(255)					,
    
    FOREIGN KEY (ID_ENTIDADE) REFERENCES ENTIDADES(ID_ENTIDADE)	,
    FOREIGN KEY (ID_PESSOA) REFERENCES PESSOAS(ID_PESSOA)		,
    CONSTRAINT CD_PRODUTO UNIQUE (ID_ENTIDADE, CD_PRODUTO)
    );
    
CREATE TABLE PRODUTO_ESTOQUE (
	ID_PRODUTO_ESTOQUE	INT PRIMARY KEY AUTO_INCREMENT	,
    ID_PRODUTO			INT NOT NULL					,
    DT_INICIO			DATE NOT NULL					,
    MIN_ESTOQUE			INT NOT NULL					,
    MED_ESTOQUE			INT NOT NULL					,
    MAX_ESTOQUE			INT NOT NULL					,
    
    CONSTRAINT DT_INICIO UNIQUE (ID_PRODUTO, DT_INICIO)
    );
    