
const querySaldo = (ID_ENTIDADE, COMPENTENCIA) => `
SELECT
    COALESCE(SUM(IF(TP_FINANCEIRO = 'R', VL_FINANCEIRO, 0)), 0) AS RECEITA,
    COALESCE(SUM(IF(TP_FINANCEIRO = 'D', VL_FINANCEIRO, 0)), 0) AS DESPESA
FROM FINANCEIRO 
WHERE CD_STATUS = 'P' 
  AND ID_ENTIDADE = ${ID_ENTIDADE}
  AND MONTH(DT_FINANCEIRO) = ${COMPENTENCIA.ID_MES} 
  AND YEAR(DT_FINANCEIRO) = ${COMPENTENCIA.ID_ANO};
`

const queryContas = (ID_ENTIDADE, COMPENTENCIA) => `
SELECT
    COALESCE(SUM(IF(TP_FINANCEIRO = 'R', VL_FINANCEIRO, 0)), 0) AS RECEITA,
    COALESCE(SUM(IF(TP_FINANCEIRO = 'D', VL_FINANCEIRO, 0)), 0) AS DESPESA
FROM FINANCEIRO 
WHERE CD_STATUS = 'L' 
  AND ID_ENTIDADE = ${ID_ENTIDADE}
  AND MONTH(DT_FINANCEIRO) = ${COMPENTENCIA.ID_MES} 
  AND YEAR(DT_FINANCEIRO) = ${COMPENTENCIA.ID_ANO};
`

const queryCategoria = (ID_ENTIDADE, COMPENTENCIA) => `
SELECT
    C.ID_CATEGORIA              ,
    C.NM_CATEGORIA              ,
    COALESCE(CO.VL_MINIMO, 0)   AS VL_MINIMO,
    COALESCE(CO.VL_MEDIO, 0)    AS VL_MEDIO,
    COALESCE(CO.VL_MAXIMO, 0)   AS VL_MAXIMO,
    
    COALESCE(SUM(IF(F.TP_FINANCEIRO = 'R', F.VL_FINANCEIRO, 0)), 0) AS TOTAL_RECEITA,
    COALESCE(SUM(IF(F.TP_FINANCEIRO = 'D', F.VL_FINANCEIRO, 0)), 0) AS TOTAL_DESPESA
    
FROM CATEGORIAS C
    INNER JOIN CATEGORIA_DETALHE CD ON CD.ID_CATEGORIA = C.ID_CATEGORIA
    
    INNER JOIN CATEGORIA_ORCAMENTO CO ON CO.ID_CATEGORIA = C.ID_CATEGORIA
        AND CO.ID_ENTIDADE = ${ID_ENTIDADE}
        AND CO.DT_INICIO = (
            SELECT MAX(CO2.DT_INICIO) 
            FROM CATEGORIA_ORCAMENTO CO2 
            WHERE C.ID_CATEGORIA = CO2.ID_CATEGORIA 
            AND CO2.ID_ENTIDADE = ${ID_ENTIDADE}
        )

    LEFT JOIN FINANCEIRO F ON F.ID_CATEGORIA_DETALHE = CD.ID_CATEGORIA_DETALHE
        AND F.ID_ENTIDADE = ${ID_ENTIDADE}
        AND MONTH(F.DT_FINANCEIRO) = ${COMPENTENCIA.ID_MES} 
        AND YEAR(F.DT_FINANCEIRO) = ${COMPENTENCIA.ID_ANO}

WHERE C.ID_ENTIDADE = ${ID_ENTIDADE}
GROUP BY 1, 2, 3, 4, 5 ORDER BY C.CD_CATEGORIA;
`

const queryProdutos = (ID_ENTIDADE, COMPENTENCIA) => `
SELECT
	P.ID_PRODUTO	,
    P.NM_PRODUTO	,
    
    CASE P.TP_PRODUTO
        WHEN 'M' THEN 'Matéria-Prima'
        WHEN 'S' THEN 'Serviço'
    END AS TP_PRODUTO,
    P.UN_MEDIDA		,
    PE.MIN_ESTOQUE	,
    PE.MED_ESTOQUE	,
    PE.MAX_ESTOQUE	,
    T.QT_SALDO		,
    
    AVG(I.VL_UNITARIO) AS VL_UNITARIO		,
    (AVG(I.VL_UNITARIO) * QT_SALDO) AS VL_TOTAL
FROM PRODUTOS P
	INNER JOIN ESTOQUE_ITENS 	I ON P.ID_PRODUTO = I.ID_PRODUTO
    
    INNER JOIN ESTOQUE			E ON I.ID_ESTOQUE = E.ID_ESTOQUE
    AND E.TP_ESTOQUE = 'E' 		AND E.CD_STATUS = 'E'
    AND E.DT_ESTOQUE = (
		SELECT MAX(E2.DT_ESTOQUE) 
		FROM ESTOQUE E2 
        INNER JOIN ESTOQUE_ITENS I2 ON E2.ID_ESTOQUE = I2.ID_ESTOQUE
		WHERE P.ID_PRODUTO = I2.ID_PRODUTO
        AND E2.TP_ESTOQUE = 'E' AND E2.CD_STATUS = 'E'
	)
    
    INNER JOIN PRODUTO_ESTOQUE PE ON PE.ID_PRODUTO = P.ID_PRODUTO
	AND PE.DT_INICIO = (
		SELECT MAX(PE2.DT_INICIO)
		FROM PRODUTO_ESTOQUE PE2
		WHERE PE2.ID_PRODUTO = P.ID_PRODUTO
	)
    
    LEFT JOIN (
		SELECT I3.ID_PRODUTO,
		SUM(IF(E3.TP_ESTOQUE = 'E', I3.QT_ITENS, -I3.QT_ITENS)) AS QT_SALDO
		FROM ESTOQUE E3
		JOIN ESTOQUE_ITENS I3 ON E3.ID_ESTOQUE = I3.ID_ESTOQUE
		WHERE E3.CD_STATUS = 'E' AND E3.ID_ENTIDADE = ${ID_ENTIDADE}
		GROUP BY I3.ID_PRODUTO
	) T ON T.ID_PRODUTO = P.ID_PRODUTO
    
WHERE P.ID_ENTIDADE = ${ID_ENTIDADE} GROUP BY 1, 2, 3, 4, 5, 6, 7 ;
`

module.exports = {
    "default": querySaldo,
	"categorias": queryCategoria,
    "contas": queryContas,
    "produtos": queryProdutos
}